# Generated by Django 5.0.1 on 2025-11-14 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код региона', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_description', models.CharField(help_text='Например: "Скидка 15%" или "2 по цене 1"', max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('partner_website', models.URLField(blank=True)),
                ('partner_category', models.CharField(help_text='Аптека, Магазин, Услуги и т.д.', max_length=100)),
                ('target_groups', models.JSONField(default=list, help_text='Список категорий льготников')),
                ('applies_to_all_regions', models.BooleanField(default=False)),
                ('locations', models.JSONField(blank=True, default=list, help_text='Адреса точек продаж')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('expiring_soon', 'Скоро истекает'), ('expired', 'Истекло')], default='active', max_length=20)),
                ('how_to_use', models.TextField(help_text='Как воспользоваться предложением')),
                ('promo_code', models.CharField(blank=True, help_text='Промокод если есть', max_length=50)),
                ('views_count', models.IntegerField(default=0)),
                ('popularity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='benefits.category')),
                ('regions', models.ManyToManyField(blank=True, related_name='offers', to='benefits.region')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_id', models.CharField(help_text='Уникальный идентификатор', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('benefit_type', models.CharField(choices=[('federal', 'Федеральная'), ('regional', 'Региональная'), ('municipal', 'Муниципальная')], max_length=20)),
                ('target_groups', models.JSONField(default=list, help_text='Список категорий льготников, например: ["pensioner", "disabled"]')),
                ('applies_to_all_regions', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expiring_soon', 'Скоро истекает'), ('expired', 'Истекла'), ('requires_verification', 'Требует верификации')], default='active', max_length=25)),
                ('requirements', models.TextField(help_text='Что нужно для получения')),
                ('how_to_get', models.TextField(help_text='Как получить эту льготу')),
                ('documents_needed', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(help_text='Источник информации', validators=[django.core.validators.URLValidator()])),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('popularity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='benefits', to='benefits.category')),
                ('regions', models.ManyToManyField(blank=True, related_name='benefits', to='benefits.region')),
            ],
            options={
                'verbose_name': 'Льгота',
                'verbose_name_plural': 'Льготы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBenefitInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Просмотр'), ('save', 'Сохранение'), ('hide', 'Скрытие'), ('export', 'Экспорт')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='benefits.benefit')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='benefits.commercialoffer')),
            ],
            options={
                'verbose_name': 'Взаимодействие пользователя',
                'verbose_name_plural': 'Взаимодействия пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
