# Generated by Django 5.0.1 on 2025-11-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbenefitinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='benefit',
            index=models.Index(fields=['benefit_type', 'status'], name='benefits_be_benefit_51e59a_idx'),
        ),
        migrations.AddIndex(
            model_name='benefit',
            index=models.Index(fields=['valid_from', 'valid_to'], name='benefits_be_valid_f_c0e47b_idx'),
        ),
    ]
