# Generated by Django 5.0.1 on 2025-11-14 14:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary_category', models.CharField(blank=True, choices=[('pensioner', 'Пенсионер'), ('disability_1', 'Инвалидность 1 группы'), ('disability_2', 'Инвалидность 2 группы'), ('disability_3', 'Инвалидность 3 группы'), ('large_family', 'Многодетная семья'), ('veteran', 'Ветеран'), ('low_income', 'Малоимущий'), ('svo_participant', 'Участник СВО'), ('svo_family', 'Семья участника СВО')], max_length=20, null=True)),
                ('region', models.CharField(help_text='Регион проживания', max_length=100)),
                ('snils', models.CharField(blank=True, help_text='Индивидуальный номер страхового счета (СНИЛС)', max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='СНИЛС должен быть в формате XXX-XXX-XXX XX', regex='^\\d{3}-\\d{3}-\\d{3} \\d{2}$')])),
                ('is_verified', models.BooleanField(default=False, help_text='Статус верификации льготника')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(choices=[('normal', 'Обычный'), ('enlarged', 'Увеличенный'), ('huge', 'Огромный')], default='normal', max_length=10)),
                ('font_family', models.CharField(choices=[('sans-serif', 'Без засечек'), ('serif', 'С засечками')], default='sans-serif', max_length=10)),
                ('letter_spacing', models.CharField(choices=[('normal', 'Обычный'), ('enlarged', 'Увеличенный'), ('huge', 'Огромный')], default='normal', max_length=10)),
                ('color_mode', models.CharField(choices=[('default', 'По умолчанию'), ('monochrome', 'Монохромный'), ('inverted', 'Инверсия'), ('blue_bg', 'Синий фон')], default='default', max_length=20)),
                ('show_images', models.BooleanField(default=True)),
                ('speech_assistant_enabled', models.BooleanField(default=False)),
                ('interest_categories', models.JSONField(blank=True, default=list)),
                ('hidden_benefits', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
                ('documents', models.JSONField(default=dict, help_text='Загруженные документы')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на верификацию',
                'verbose_name_plural': 'Запросы на верификацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
